const GET_ALLGAMES = "GET_ALLGAMES";
const GET_GAME = "GET_GAMES";
const FILTER_GENRES = "FILTER_GENRES";
const FILTER_ORIGIN = "FILTER_ORIGIN";
const ORDER = "ORDER";
const ALPHABETH = "ALPHABETH";
const GET_VIDEOGAME_BY_NAME = "GET_VIDEOGAME_BY_NAME";

export {GET_VIDEOGAME_BY_NAME, ALPHABETH, ORDER, FILTER_ORIGIN, FILTER_GENRES, GET_GAME, GET_ALLGAMES }
