const GET_VIDEOGAME_BY_NAME = 'GET_VIDEOGAME_BY_NAME'
const SET_PAGE_TO_ONE = 'SET_PAGE_TO_ONE'
const FILTER_GENRES = 'FILTER_GENRES'
const FILTER_ORIGIN = 'FILTER_ORIGIN'
const GET_ALLGAMES = 'GET_ALLGAMES'
const ALPHABETH = 'ALPHABETH'
const ORDER = 'ORDER'

export { GET_VIDEOGAME_BY_NAME, SET_PAGE_TO_ONE, FILTER_GENRES, FILTER_ORIGIN, GET_ALLGAMES, ALPHABETH, ORDER }